-- Create reports table for Supabase
-- Run this SQL in your Supabase SQL Editor

CREATE TABLE reports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  severity VARCHAR(50) NOT NULL DEFAULT 'low',
  location_lat DECIMAL(10, 8) NOT NULL,
  location_lng DECIMAL(11, 8) NOT NULL,
  image_url TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX idx_reports_severity ON reports(severity);
CREATE INDEX idx_reports_status ON reports(status);
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);

-- Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Allow anyone to select reports
CREATE POLICY "Reports are viewable by everyone"
ON reports FOR SELECT
USING (true);

-- Allow anyone to insert reports
CREATE POLICY "Anyone can insert reports"
ON reports FOR INSERT
WITH CHECK (true);

-- Allow updates to anyone (for admin status changes)
CREATE POLICY "Anyone can update report status"
ON reports FOR UPDATE
USING (true)
WITH CHECK (true);
